// --==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==
// DATA FILES FOR THE BATTLE SIM, CHANGE THINGS HERE
// MONSTERS, WEAPONS, ETC.
// --==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==

var monsters = [
	{
		name:"Zombieman Trio",
		health:60,
		hasMelee:false,
		hasRanged:true,
		rangedMin:9,
		rangedMax:45,
		rangedString:"shot at PLAYER",
		meleeMin:-1,
		meleeMax:-1,
		meleeString:"",
		sightsprite:"3zombiesight",
		idlesprite:"3zombiedie",
		rangedsprite:"3zombieshoot",
		meleesprite:"3zombieidle",
		deathsprite:"3zombiedie",
		painsprite:"3zombieidle",
		gibsprite:"3zombiegib",
		gibhealth:-20,
		soundsight:["DSPOSIT1","DSPOSIT2","DSPOSIT3"],
		soundidle:["DSPOSACT"],
		soundranged:["DSPISTOL"],
		soundmelee:["DSPISTOL"],
		sounddeath:["DSPODTH1","DSPODTH2","DSPODTH3"],
		soundgib:["DSSLOP"]
	},
	{
		name:"Mastermind Duo",
		health:6000,
		hasMelee:false,
		hasRanged:true,
		rangedMin:65,
		rangedMax:90,
		rangedString:"shot barrages at PLAYER",
		meleeMin:-1,
		meleeMax:-1,
		meleeString:"",
		sightsprite:"2spidersight",
		idlesprite:"2spideridle",
		rangedsprite:"2spidershoot",
		meleesprite:"2spideridle",
		deathsprite:"2spiderdie",
		painsprite:"2spideridle",
		gibsprite:"2spiderdie",
		gibhealth:-5000,
		soundsight:["DSSPISIT"],
		soundidle:["DSMETAL"],
		soundranged:["spiderfire"],
		soundmelee:["spiderfire"],
		sounddeath:["DSSPIDTH"],
		soundgib:["DSSPIDTH"]
	},
	{
		name:"Pinky Demon",
		health:150,
		hasMelee:true,
		hasRanged:false,
		rangedMin:-1,
		rangedMax:-1,
		rangedString:"",
		meleeMin:4,
		meleeMax:40,
		meleeString:"bit PLAYER",
		sightsprite:"demonsight",
		idlesprite:"demonidle",
		rangedsprite:"demonbite",
		meleesprite:"demonbite",
		deathsprite:"demondie",
		painsprite:"demonpain",
		gibsprite:"demondie",
		gibhealth:-5000,
		soundsight:["DSSGTSIT"],
		soundidle:["DSPOSACT"],
		soundranged:["DSSGTATK"],
		soundmelee:["DSSGTATK"],
		sounddeath:["DSSGTDTH"],
		soundgib:["DSSLOP"]
	},
	{
		name:"Zombieman",
		health:20,
		hasMelee:false,
		hasRanged:true,
		rangedMin:3,
		rangedMax:15,
		rangedString:"shot at PLAYER",
		meleeMin:-1,
		meleeMax:-1,
		meleeString:"",
		sightsprite:"zombiesight",
		idlesprite:"zombiedie",
		rangedsprite:"zombieshoot",
		meleesprite:"zombieidle",
		deathsprite:"zombiedie",
		painsprite:"zombiepain",
		gibsprite:"zombiegib",
		gibhealth:-20,
		soundsight:["DSPOSIT1","DSPOSIT2","DSPOSIT3"],
		soundidle:["DSPOSACT"],
		soundranged:["DSPISTOL"],
		soundmelee:["DSPISTOL"],
		sounddeath:["DSPODTH1","DSPODTH2","DSPODTH3"],
		soundgib:["DSSLOP"]
	},
	{
		name:"Cyberdemon",
		health:4000,
		hasMelee:false,
		hasRanged:true,
		rangedMin:20,
		rangedMax:80,
		rangedString:"shot three rockets at PLAYER",
		meleeMin:-1,
		meleeMax:-1,
		meleeString:"",
		sightsprite:"cybersight",
		idlesprite:"cyberidle",
		rangedsprite:"cybershoot",
		meleesprite:"cyberidle",
		deathsprite:"cyberdie",
		painsprite:"cyberpain",
		gibsprite:"cyberdie",
		gibhealth:-5000,
		soundsight:["DSCYBSIT"],
		soundidle:["DSHOOF"],
		soundranged:["DSRLAUNC"],
		soundmelee:["DSRLAUNC"],
		sounddeath:["DSCYBDTH"],
		soundgib:["DSCYBDTH"]
	},
	{
		name:"Spider Mastermind",
		health:3000,
		hasMelee:false,
		hasRanged:true,
		rangedMin:45,
		rangedMax:65,
		rangedString:"shot a barrage at PLAYER",
		meleeMin:-1,
		meleeMax:-1,
		meleeString:"",
		sightsprite:"spidersight",
		idlesprite:"spideridle",
		rangedsprite:"spidershoot",
		meleesprite:"spideridle",
		deathsprite:"spiderdie",
		painsprite:"spideridle",
		gibsprite:"spiderdie",
		gibhealth:-5000,
		soundsight:["DSSPISIT"],
		soundidle:["DSMETAL"],
		soundranged:["spiderfire"],
		soundmelee:["spiderfire"],
		sounddeath:["DSSPIDTH"],
		soundgib:["DSSPIDTH"]
	},
	{
		name:"Revenant",
		health:300,
		hasMelee:true,
		hasRanged:true,
		rangedMin:20,
		rangedMax:60,
		rangedString:"shot a rocket at PLAYER",
		meleeMin:8,
		meleeMax:64,
		meleeString:"bitchslapped PLAYER",
		sightsprite:"revsight",
		idlesprite:"revidle",
		rangedsprite:"revranged",
		meleesprite:"revmelee",
		deathsprite:"revdie",
		painsprite:"revidle",
		gibsprite:"revdie",
		gibhealth:-5000,
		soundsight:["DSSKESIT"],
		soundidle:["DSSKEACT"],
		soundranged:["DSSKEATK"],
		soundmelee:["DSSKEPCH"],
		sounddeath:["DSSKEDTH"],
		soundgib:["DSSKEDTH"]
	},
	{
		name:"Arch-Vile",
		health:700,
		hasMelee:false,
		hasRanged:true,
		rangedMin:70,
		rangedMax:80,
		rangedString:"incinerated PLAYER",
		meleeMin:-1,
		meleeMax:-1,
		meleeString:"",
		sightsprite:"vilesight",
		idlesprite:"vileidle",
		rangedsprite:"vileranged",
		meleesprite:"vileranged",
		deathsprite:"viledeath",
		painsprite:"vileidle",
		gibsprite:"viledeath",
		gibhealth:-20,
		soundsight:["DSVILSIT"],
		soundidle:["DSVILACT"],
		soundranged:["DSVILATK"],
		soundmelee:["DSVILATK"],
		sounddeath:["DSVILDTH"],
		soundgib:["DSVILDTH"]
	}
];

module.exports = monsters;